-- Project2AK — derived views.
--
-- Every number the app displays that isn't typed by the user is computed
-- here. The spreadsheet this replaces had formula rows 8,000+ characters wide
-- that broke whenever a row was inserted; the point of moving the logic into
-- SQL is that it is inspectable, testable, and can't be clobbered by an edit.
--
-- All views are security_invoker so the caller's RLS applies. A view without
-- it runs as its owner and leaks every row.
--
-- Pending transactions (generated by a recurring rule, not yet confirmed) are
-- excluded from every balance and actual. They only appear in the confirmation
-- queue and in the safe-to-spend projection, where the whole point is that
-- they haven't happened yet.

-- ------------------------------------------------------------- helpers ----

-- Next date strictly after `from_date` matching one of the payday days,
-- clamping to month end (a 31st payday lands on the 30th in November).
create or replace function next_payday(days int[], from_date date)
returns date
language sql
immutable
as $$
  select min(c.candidate)
  from unnest(days) as d
  cross join generate_series(0, 2) as offs
  cross join lateral (
    select (date_trunc('month', from_date) + make_interval(months => offs))::date as month_start
  ) m
  cross join lateral (
    select (
      m.month_start
      + (least(d, extract(day from (m.month_start + interval '1 month - 1 day'))::int) - 1)
    )::date as candidate
  ) c
  where c.candidate > from_date;
$$;

-- ------------------------------------------------- v_account_balances -----

-- opening + transactions + transfers in - transfers out. Balances are ALWAYS
-- derived; the spreadsheet's hand-typed balances drifted from the logged
-- transactions within weeks.
create view v_account_balances with (security_invoker = true) as
select
  a.id                                as account_id,
  a.user_id,
  a.name,
  a.type,
  a.is_active,
  a.sort_order,
  a.opening_date,
  a.opening_balance_centavos,
  a.apr,
  a.due_day,
  a.late_fee_centavos,
  a.credit_limit_centavos,
  a.tracking_mode,
  a.closed_at,
  a.closure_confirmed,
  a.closure_note,
  coalesce(tx.total, 0)               as transactions_centavos,
  coalesce(tin.total, 0)              as transfers_in_centavos,
  coalesce(tout.total, 0)             as transfers_out_centavos,
  a.opening_balance_centavos
    + coalesce(tx.total, 0)
    + coalesce(tin.total, 0)
    - coalesce(tout.total, 0)         as balance_centavos,
  (a.type in ('bank', 'ewallet', 'cash')) as is_liquid,
  (a.type in ('credit', 'loan'))          as is_liability,
  -- An account at ₱0 that was never confirmed closed with the provider is
  -- NOT finished: the credit is available again. Surfaced as a warning.
  (a.type in ('credit', 'loan')
   and a.closed_at is null
   and (a.opening_balance_centavos + coalesce(tx.total, 0)
        + coalesce(tin.total, 0) - coalesce(tout.total, 0)) >= 0) as needs_closing
from accounts a
left join lateral (
  select sum(t.amount_centavos) as total
  from transactions t
  where t.account_id = a.id and t.deleted_at is null and not t.is_pending
) tx on true
left join lateral (
  select sum(tr.amount_centavos) as total
  from transfers tr
  where tr.to_account_id = a.id and tr.deleted_at is null and not tr.is_pending
) tin on true
left join lateral (
  select sum(tr.amount_centavos) as total
  from transfers tr
  where tr.from_account_id = a.id and tr.deleted_at is null and not tr.is_pending
) tout on true
where a.deleted_at is null;

-- ------------------------------------------------- v_monthly_actuals ------

create view v_monthly_actuals with (security_invoker = true) as
select
  t.user_id,
  t.category_id,
  extract(year  from t.date)::int as year,
  extract(month from t.date)::int as month,
  sum(t.amount_centavos)         as net_centavos,
  count(*)::int                  as txn_count
from transactions t
where t.deleted_at is null
  and not t.is_pending
  and t.category_id is not null
group by 1, 2, 3, 4;

-- ----------------------------------------------- v_budget_vs_actual -------

-- The 12-months × category grid, with rollover.
--
-- Rollover is what makes this zero-based budgeting rather than twelve
-- unrelated budgets: overspend carries forward as negative, underspend
-- accumulates. It accumulates across year boundaries deliberately — a
-- December overspend that vanishes on 1 January is the exact bug this
-- replaces.
create view v_budget_vs_actual with (security_invoker = true) as
with bounds as (
  select
    p.user_id,
    least(
      p.active_year,
      coalesce((select min(b.year) from budgets b where b.user_id = p.user_id), p.active_year),
      coalesce((select min(extract(year from t.date))::int
                from transactions t
                where t.user_id = p.user_id and t.deleted_at is null and not t.is_pending),
               p.active_year)
    ) as min_year,
    greatest(
      p.active_year,
      coalesce((select max(b.year) from budgets b where b.user_id = p.user_id), p.active_year),
      coalesce((select max(extract(year from t.date))::int
                from transactions t
                where t.user_id = p.user_id and t.deleted_at is null and not t.is_pending),
               p.active_year)
    ) as max_year
  from profiles p
),
spine as (
  select
    c.user_id,
    c.id             as category_id,
    c."group"        as category_group,
    c.name           as category_name,
    c.rollover_enabled,
    c.due_day,
    c.sort_order,
    c.is_archived,
    y.year::int      as year,
    m.month::int     as month
  from categories c
  join bounds bd on bd.user_id = c.user_id
  cross join lateral generate_series(bd.min_year, bd.max_year) as y(year)
  cross join generate_series(1, 12) as m(month)
  where c.deleted_at is null
),
joined as (
  select
    s.*,
    coalesce(b.amount_centavos, 0) as budget_centavos,
    coalesce(b.is_paid, false)     as is_paid,
    -- Actuals become a positive magnitude in the natural direction for the
    -- group, so they compare directly against the (unsigned) budget.
    case when s.category_group = 'income'
         then  coalesce(a.net_centavos, 0)
         else -coalesce(a.net_centavos, 0)
    end                            as actual_centavos,
    coalesce(a.txn_count, 0)       as txn_count
  from spine s
  left join budgets b
    on b.category_id = s.category_id and b.year = s.year and b.month = s.month
  left join v_monthly_actuals a
    on a.category_id = s.category_id and a.year = s.year and a.month = s.month
),
rolled as (
  select
    j.*,
    case when j.rollover_enabled then
      coalesce(
        sum(j.budget_centavos - j.actual_centavos) over (
          partition by j.category_id
          order by j.year, j.month
          rows between unbounded preceding and 1 preceding
        ), 0)
    else 0 end as rollover_in_centavos
  from joined j
)
select
  user_id,
  category_id,
  category_group,
  category_name,
  rollover_enabled,
  is_archived,
  due_day,
  sort_order,
  year,
  month,
  budget_centavos,
  is_paid,
  actual_centavos,
  txn_count,
  rollover_in_centavos,
  budget_centavos + rollover_in_centavos                     as available_centavos,
  budget_centavos + rollover_in_centavos - actual_centavos   as remaining_centavos,
  budget_centavos - actual_centavos                          as variance_centavos
from rolled;

-- ----------------------------------------------------- v_safe_to_spend ----

-- Nobody wakes up asking about variance to budget. They ask "can I afford
-- this right now". Liquid balances, minus everything already committed
-- before the next payday.
create view v_safe_to_spend with (security_invoker = true) as
with pay as (
  select p.user_id, next_payday(p.payday_days, current_date) as payday
  from profiles p
),
liquid as (
  select b.user_id, sum(b.balance_centavos) as total
  from v_account_balances b
  where b.is_liquid and b.is_active
  group by 1
),
-- Pending rows a rule already generated but the user hasn't confirmed.
pending_out as (
  select t.user_id, sum(-t.amount_centavos) as total
  from transactions t
  join accounts a on a.id = t.account_id
  join pay        on pay.user_id = t.user_id
  where t.deleted_at is null and t.is_pending
    and t.amount_centavos < 0
    and t.date <= pay.payday
    and a.type in ('bank', 'ewallet', 'cash')
  group by 1
),
pending_transfers as (
  select tr.user_id, sum(tr.amount_centavos) as total
  from transfers tr
  join accounts a on a.id = tr.from_account_id
  join pay        on pay.user_id = tr.user_id
  where tr.deleted_at is null and tr.is_pending
    and tr.date <= pay.payday
    and a.type in ('bank', 'ewallet', 'cash')
  group by 1
),
-- Rules due before payday that haven't generated their row yet. Without this
-- the projection is optimistic for the window between "bill is due" and "the
-- generator has run".
rule_out as (
  select
    r.user_id,
    sum(
      case
        when r.to_account_id is not null
          then coalesce(r.amount_centavos, last_tr.amt, 0)
        else greatest(-coalesce(r.amount_centavos, last_tx.amt, 0), 0)
      end
    ) as total
  from recurring_rules r
  join pay        on pay.user_id = r.user_id
  join accounts a on a.id = r.account_id
  left join lateral (
    select t.amount_centavos as amt
    from transactions t
    where t.recurring_rule_id = r.id and t.deleted_at is null
    order by t.date desc limit 1
  ) last_tx on true
  left join lateral (
    select tr.amount_centavos as amt
    from transfers tr
    where tr.recurring_rule_id = r.id and tr.deleted_at is null
    order by tr.date desc limit 1
  ) last_tr on true
  where r.is_active and r.deleted_at is null
    and r.next_run <= pay.payday
    and a.type in ('bank', 'ewallet', 'cash')
    and not exists (
      select 1 from transactions t2
      where t2.recurring_rule_id = r.id and t2.date = r.next_run and t2.deleted_at is null
    )
    and not exists (
      select 1 from transfers tr2
      where tr2.recurring_rule_id = r.id and tr2.date = r.next_run and tr2.deleted_at is null
    )
  group by 1
)
select
  p.user_id,
  pay.payday                                as next_payday,
  (pay.payday - current_date)::int          as days_to_payday,
  coalesce(l.total, 0)                      as liquid_centavos,
  coalesce(po.total, 0)
    + coalesce(pt.total, 0)
    + coalesce(ro.total, 0)                 as committed_centavos,
  coalesce(l.total, 0)
    - coalesce(po.total, 0)
    - coalesce(pt.total, 0)
    - coalesce(ro.total, 0)                 as safe_to_spend_centavos
from profiles p
join pay                on pay.user_id = p.user_id
left join liquid l      on l.user_id  = p.user_id
left join pending_out po on po.user_id = p.user_id
left join pending_transfers pt on pt.user_id = p.user_id
left join rule_out ro   on ro.user_id = p.user_id;

-- --------------------------------------------------- v_savings_progress ---

-- Two savings types, which the spreadsheet conflated:
--   goal    — accumulates to a target, then done (emergency fund, wedding)
--   sinking — fills, gets spent, refills (Christmas, yearly car expenses)
-- A sinking fund at ₱0 in January is the cycle working, not a failure.
--
-- A goal tracks either a dedicated account (the transfer model — salary lands
-- in the bank, a transfer moves it to savings) or a budget category (the
-- sinking-fund model, where the contribution is a budgeted line item).
create view v_savings_progress with (security_invoker = true) as
select
  g.id                          as goal_id,
  g.user_id,
  g.category_id,
  g.account_id,
  c.name                        as category_name,
  g.kind,
  g.beneficiary,
  g.goal_amount_centavos,
  g.monthly_amount_centavos,
  g.target_date,
  coalesce(
    ab.balance_centavos,
    g.starting_amount_centavos + coalesce(cat.contributed, 0)
  )                             as saved_centavos,
  case
    when g.goal_amount_centavos is null or g.goal_amount_centavos = 0 then null
    else greatest(
      g.goal_amount_centavos
        - coalesce(ab.balance_centavos,
                   g.starting_amount_centavos + coalesce(cat.contributed, 0)),
      0)
  end                           as remaining_centavos,
  case
    when g.goal_amount_centavos is null or g.goal_amount_centavos = 0 then null
    else round(
      100.0 * coalesce(ab.balance_centavos,
                       g.starting_amount_centavos + coalesce(cat.contributed, 0))
      / g.goal_amount_centavos, 1)
  end                           as percent_complete,
  case
    when g.goal_amount_centavos is null
      or g.monthly_amount_centavos is null
      or g.monthly_amount_centavos <= 0 then null
    else ceil(
      greatest(
        g.goal_amount_centavos
          - coalesce(ab.balance_centavos,
                     g.starting_amount_centavos + coalesce(cat.contributed, 0)),
        0)::numeric / g.monthly_amount_centavos)::int
  end                           as months_remaining
from savings_goals g
join categories c on c.id = g.category_id
left join v_account_balances ab on ab.account_id = g.account_id
left join lateral (
  -- Money moved into a savings category reads as an outflow from the
  -- spending side, so flip the sign to get the contribution.
  select -sum(t.amount_centavos) as contributed
  from transactions t
  where t.category_id = g.category_id
    and t.deleted_at is null and not t.is_pending
) cat on true
where g.deleted_at is null;

-- The 2AK line: goals tagged for a beneficiary sum into one quiet number,
-- with its change this month. Untagged goals behave exactly as before.
create view v_beneficiary_totals with (security_invoker = true) as
select
  g.user_id,
  g.beneficiary,
  sum(sp.saved_centavos)                                   as saved_centavos,
  coalesce(sum(-mtd.delta), 0)                             as change_this_month_centavos
from savings_goals g
join v_savings_progress sp on sp.goal_id = g.id
left join lateral (
  select sum(t.amount_centavos) as delta
  from transactions t
  where t.category_id = g.category_id
    and t.deleted_at is null and not t.is_pending
    and t.date >= date_trunc('month', current_date)::date
) mtd on true
where g.deleted_at is null and g.beneficiary is not null
group by 1, 2;

-- ------------------------------------------------------ v_debt_progress ---

-- Six BNPL accounts plus a personal loan is the most consequential thing in
-- this data, and the spreadsheet only recorded it.
--
-- Deriving payments as lag(balance) - balance merged principal and interest
-- into one number. Here they stay separate: payments are transfers in,
-- charges are negative transactions, and the gap against the statement
-- balance is unlogged interest or fees.
create view v_debt_progress with (security_invoker = true) as
select
  b.account_id,
  b.user_id,
  b.name,
  b.type,
  b.apr,
  b.due_day,
  b.late_fee_centavos,
  b.credit_limit_centavos,
  b.tracking_mode,
  b.closed_at,
  b.closure_confirmed,
  b.closure_note,
  b.needs_closing,
  -- Positive magnitude of what is owed. A liability carries a negative
  -- balance, so flip it once, here, and never think about it again.
  greatest(-b.balance_centavos, 0)              as owed_centavos,
  b.balance_centavos                            as derived_balance_centavos,
  st.statement_balance_centavos,
  st.month                                      as statement_month,
  -- Negative gap means the provider says you owe more than you've logged:
  -- unlogged interest or fees, bookable as an adjustment to Finance Charges.
  case when st.statement_balance_centavos is null then null
       else b.balance_centavos - st.statement_balance_centavos
  end                                           as statement_gap_centavos,
  coalesce(pay.total, 0)                        as payments_centavos,
  coalesce(chg.total, 0)                        as charges_centavos,
  case when coalesce(chg.total, 0) = 0 then null
       else round(100.0 * coalesce(pay.total, 0) / chg.total, 1)
  end                                           as percent_paid,
  coalesce(recent.avg_monthly, 0)               as avg_monthly_payment_centavos,
  case
    when coalesce(recent.avg_monthly, 0) <= 0 then null
    when greatest(-b.balance_centavos, 0) = 0 then 0
    else ceil(greatest(-b.balance_centavos, 0)::numeric / recent.avg_monthly)::int
  end                                           as months_to_payoff
from v_account_balances b
left join lateral (
  select s.statement_balance_centavos, s.month
  from account_statements s
  where s.account_id = b.account_id
  order by s.month desc limit 1
) st on true
left join lateral (
  select sum(tr.amount_centavos) as total
  from transfers tr
  where tr.to_account_id = b.account_id and tr.deleted_at is null and not tr.is_pending
) pay on true
left join lateral (
  select sum(-t.amount_centavos) as total
  from transactions t
  where t.account_id = b.account_id and t.deleted_at is null and not t.is_pending
    and t.amount_centavos < 0
) chg on true
left join lateral (
  select (sum(tr.amount_centavos) / 6.0) as avg_monthly
  from transfers tr
  where tr.to_account_id = b.account_id and tr.deleted_at is null and not tr.is_pending
    and tr.date >= (current_date - interval '6 months')::date
) recent on true
where b.is_liability;

-- ------------------------------------------------------ v_reconciliation --

-- Monthly, the user enters the real statement balance per account. The delta
-- against the derived balance catches missed transactions without corrupting
-- history.
create view v_reconciliation with (security_invoker = true) as
select
  b.account_id,
  b.user_id,
  b.name,
  b.type,
  b.is_liquid,
  b.is_liability,
  b.balance_centavos                              as derived_centavos,
  st.statement_balance_centavos,
  st.month                                        as statement_month,
  st.reconciled_at,
  case when st.statement_balance_centavos is null then null
       else st.statement_balance_centavos - b.balance_centavos
  end                                             as delta_centavos
from v_account_balances b
left join lateral (
  select s.statement_balance_centavos, s.month, s.reconciled_at
  from account_statements s
  where s.account_id = b.account_id
  order by s.month desc limit 1
) st on true
where b.is_active;

-- ------------------------------------------------------ v_no_spend_days ---

-- Every day of the active year flagged. Expenses group only — a mortgage
-- payment landing on the 28th is not a failure of restraint.
create view v_no_spend_days with (security_invoker = true) as
select
  p.user_id,
  d.day::date                                   as day,
  extract(year  from d.day)::int                as year,
  extract(month from d.day)::int                as month,
  coalesce(sp.spent, 0)                         as spent_centavos,
  (coalesce(sp.spent, 0) = 0)                   as is_no_spend,
  (d.day <= current_date)                       as is_elapsed
from profiles p
cross join lateral generate_series(
  make_date(p.active_year, 1, 1),
  make_date(p.active_year, 12, 31),
  interval '1 day'
) as d(day)
left join lateral (
  select sum(-t.amount_centavos) as spent
  from transactions t
  join categories c on c.id = t.category_id
  where t.user_id = p.user_id
    and t.date = d.day::date
    and t.deleted_at is null and not t.is_pending
    and t.amount_centavos < 0
    and c."group" = 'expenses'
) sp on true;

-- --------------------------------------------------- v_net_worth_monthly --

-- Account balances at each month end, plus manual non-cash items.
create view v_net_worth_monthly with (security_invoker = true) as
with bounds as (
  select
    p.user_id,
    coalesce(
      (select min(a.opening_date) from accounts a
       where a.user_id = p.user_id and a.deleted_at is null),
      date_trunc('year', current_date)::date
    ) as start_date
  from profiles p
),
months as (
  select
    bd.user_id,
    date_trunc('month', m.month)::date as month,
    (date_trunc('month', m.month) + interval '1 month - 1 day')::date as month_end
  from bounds bd
  cross join lateral generate_series(
    date_trunc('month', bd.start_date),
    date_trunc('month', current_date),
    interval '1 month'
  ) as m(month)
),
account_totals as (
  select
    mo.user_id,
    mo.month,
    sum(
      case when a.opening_date <= mo.month_end then a.opening_balance_centavos else 0 end
      + coalesce(tx.total, 0) + coalesce(tin.total, 0) - coalesce(tout.total, 0)
    ) as total
  from months mo
  join accounts a on a.user_id = mo.user_id and a.deleted_at is null
  left join lateral (
    select sum(t.amount_centavos) as total from transactions t
    where t.account_id = a.id and t.deleted_at is null and not t.is_pending
      and t.date <= mo.month_end
  ) tx on true
  left join lateral (
    select sum(tr.amount_centavos) as total from transfers tr
    where tr.to_account_id = a.id and tr.deleted_at is null and not tr.is_pending
      and tr.date <= mo.month_end
  ) tin on true
  left join lateral (
    select sum(tr.amount_centavos) as total from transfers tr
    where tr.from_account_id = a.id and tr.deleted_at is null and not tr.is_pending
      and tr.date <= mo.month_end
  ) tout on true
  group by 1, 2
),
manual_totals as (
  select
    mo.user_id,
    mo.month,
    sum(
      case when i.is_liability then -v.amount_centavos else v.amount_centavos end
    ) as total
  from months mo
  join net_worth_items i on i.user_id = mo.user_id and i.deleted_at is null
  join lateral (
    select nv.amount_centavos
    from net_worth_values nv
    where nv.item_id = i.id and nv.month <= mo.month
    order by nv.month desc limit 1
  ) v on true
  group by 1, 2
)
select
  mo.user_id,
  mo.month,
  coalesce(at.total, 0)                       as accounts_centavos,
  coalesce(mt.total, 0)                       as manual_centavos,
  coalesce(at.total, 0) + coalesce(mt.total, 0) as net_worth_centavos
from months mo
left join account_totals at on at.user_id = mo.user_id and at.month = mo.month
left join manual_totals  mt on mt.user_id = mo.user_id and mt.month = mo.month;
